package com.project.code.Model;

import jakarta.validation.constraints.NotNull;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

// 7. @Document marks this class as a MongoDB document in the "reviews" collection
@Document(collection = "reviews")
public class Review {

    // 9. 'id' field - unique identifier, auto-generated by MongoDB
    @Id
    private String id;

    // 1. 'customerId' field - cannot be null
    @NotNull(message = "Customer cannot be null")
    private Long customerId;

    // 2. 'productId' field - cannot be null
    @NotNull(message = "Product cannot be null")
    private Long productId;

    // 3. 'storeId' field - cannot be null
    @NotNull(message = "Store cannot be null")
    private Long storeId;

    // 4. 'rating' field - cannot be null
    @NotNull(message = "Rating cannot be null")
    private Integer rating;

    // 5. 'comment' field - optional, no @NotNull
    private String comment;

    // 8. No-argument constructor (required by Spring Data MongoDB)
    public Review() {}

    // 8. Parameterized constructor
    public Review(Long customerId, Long productId, Long storeId, Integer rating, String comment) {
        this.customerId = customerId;
        this.productId = productId;
        this.storeId = storeId;
        this.rating = rating;
        this.comment = comment;
    }

    // 10. Getters and Setters

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public Long getCustomerId() { return customerId; }
    public void setCustomerId(Long customerId) { this.customerId = customerId; }

    public Long getProductId() { return productId; }
    public void setProductId(Long productId) { this.productId = productId; }

    public Long getStoreId() { return storeId; }
    public void setStoreId(Long storeId) { this.storeId = storeId; }

    public Integer getRating() { return rating; }
    public void setRating(Integer rating) { this.rating = rating; }

    public String getComment() { return comment; }
    public void setComment(String comment) { this.comment = comment; }
}
